/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    DriverEditModal: typeof import('./src/components/DriverEditModal.vue')['default']
    DriverEntryInlineForm: typeof import('./src/components/DriverEntryInlineForm.vue')['default']
    DriverSelectModal: typeof import('./src/components/DriverSelectModal.vue')['default']
    EntryListItem: typeof import('./src/components/EntryListItem.vue')['default']
    EntryOptionToggle: typeof import('./src/components/EntryOptionToggle.vue')['default']
    FilePicker: typeof import('./src/components/FilePicker.vue')['default']
    FormItemInfo: typeof import('./src/components/FormItemInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
