/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: (typeof import('bootstrap-vue-next'))['BCard']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-next')['BFormSelectOption']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BIcon: (typeof import('bootstrap-vue-next'))['BIcon']
    BLink: (typeof import('bootstrap-vue-next'))['BLink']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    FilePicker: typeof import('./src/components/FilePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
